<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIWxxQyT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIWxxQyT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIWxxQyT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIWxxQyT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIWxxQyT\App_KernelDevDebugContainer([
    'container.build_hash' => 'IWxxQyT',
    'container.build_id' => '6dac5e52',
    'container.build_time' => 1582335851,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIWxxQyT');
