<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMKC75ZX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMKC75ZX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMKC75ZX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMKC75ZX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMKC75ZX\App_KernelDevDebugContainer([
    'container.build_hash' => 'MKC75ZX',
    'container.build_id' => 'c33826c5',
    'container.build_time' => 1582329687,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMKC75ZX');
