<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI72liFr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI72liFr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerI72liFr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerI72liFr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerI72liFr\App_KernelDevDebugContainer([
    'container.build_hash' => 'I72liFr',
    'container.build_id' => '0ff9af0c',
    'container.build_time' => 1582335008,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI72liFr');
